### ISSUE TITLE
License inconsistency betweent the LICENSE file and the setup.cfg metadata

### ISSUE THREAD

**Issue by mattip** [bigcat88/pillow_heif#111]
The LICENSE says Apache2, the setup.cfg [says](https://github.com/bigcat88/pillow_heif/blob/d1da3364b3d6ed854b49645fa52a07deba16c7fa/setup.cfg#L25) GPL2. The underlying `libheif` is LGPL3. Found this by digging into the list of projects from [this comment](https://github.com/numpy/numpy/pull/24138#discussion_r1258674884) on  numpy/numpy#24138. Did I read things right here?

**Comment by bigcat88** [comment]
`x265` HEVC encoder has GPL2.
`libheif` as you say has LGPL3.
Sources of the `pillow_heif` is under Apache2.

GPL2 is license for binary wheels, as `x265` binaries are in the wheels.


P.S.: I have a solution for that in mind, as latest `libheif` supports plugins, need to check idea on the `musl` based OS, if ok LICENSE will be Apache2(source)/LGPL3(wheels) for `pillow_heif`.

**Comment by mattip** [comment]
I think Apache2 and GPL2 are incompatible licenses, from the middle of https://www.apache.org/licenses/GPL-compatibility.html: 
> Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license. The Apache Software Foundation believes that you should always try to obey the constraints expressed by the copyright holder when redistributing their work.

**Comment by bigcat88** [comment]
I will change the license to `BSD 3-Clause` from the next release.
Thank you for pointing it out.

**Comment by mattip** [comment]
:+1: Thanks for providing this wrapper

**Comment by mattip** [comment]
Thanks
