### ISSUE TITLE
DLL load failed while importing libheif

### ISSUE THREAD

**Issue by ttjhninn** [bigcat88/pillow_heif#12]
As running the example, there is an error happened while importing ffi, lib form pillow_heif.libheif. Any suggestion, plz?

from pillow_heif.libheif import ffi, lib  # pylint: disable=import-error, no-name-in-module.
ImportError: DLL load failed while importing libheif:

**Comment by bigcat88** [comment]
@ttjhninn wha type of error? cyclic import?
do you install it before import?

**Comment by ttjhninn** [comment]
@bigcat88  

Enviroment:   Spyder(Python 3.9) on Win10

1. Do you install it before import
    -> I executed "pip install pillow_heif". As I executed "pip show pillow_heif", I could see the information as below:

        - Name: pillow-heif
        - Version: 0.1.6
        - Summary: Python 3.6+ interface to libheif library
        - Home-page: https://github.com/bigcat88/pillow_heif
        - Author: Alexander Piskun
        - Author-email: bigcat88@users.noreply.github.com
        - License: Apache-2.0
        - Location: c:\users\06045\anaconda3\lib\site-packages
        - Requires: Pillow, cffi
        - Required-by: 
        - Note: you may need to restart the kernel to use updated packages.

----------------------------------------------------------------------------------------------------------------------
I'm not sure if it happened because of "cyclic import". 

from PIL import Image
import pillow_heif

------>>>>>
runfile('E:/xx/xx/xx/xx/test/untitled1.py', wdir='E:/xx/xx/xx/xx/test')
Traceback (most recent call last):

  File "E:\xx\xx\xx\xx\test\untitled1.py", line 2, in <module>
    import pillow_heif

  File "C:\Users\xx\Anaconda3\lib\site-packages\pillow_heif\__init__.py", line 43, in <module>
    from .reader import (

  File "C:\Users\xx\Anaconda3\lib\site-packages\pillow_heif\reader.py", line 11, in <module>
    from pillow_heif.libheif import ffi, lib  # pylint: disable=import-error, no-name-in-module

ImportError: DLL load failed while importing libheif: The specified module could not be found.

**Comment by bigcat88** [comment]
@ttjhninn will look at it today.

**Comment by bigcat88** [comment]
@ttjhninn can't reproduce.
Installed Python3.10 on Windows 10, and all is ok.
Can you test with cffi `1.15.0` ?

**Comment by ttjhninn** [comment]
@bigcat88 It works now!

1.  I update the version of cfffi to ver.1.15.0, failed.
2. I download Python 3.10, which can't be employed in Spyder IDE, and it works!
3. now i can execute the example code based on Python3.10 + VS code.

Thanks for the help~~

**Comment by bigcat88** [comment]
@ttjhninn do i need to check if is this related to Spyder IDE? Can you check last version for such behaviour? (i renamed cffi module and maybe that will help in this situations)

**Comment by ttjhninn** [comment]
@bigcat88  After upgrade pillow_heif to version = 0.1.7, i can execute the sample code on Spyder IDE based on Python3.9 now.
