### ISSUE TITLE
AttributeError when calling Image.verify()

### ISSUE THREAD

**Issue by zijian-hu** [bigcat88/pillow_heif#13]
## Problem description

When calling `Image.verify()` on a `.heic` image, the program raise an `AttributeError` exception with the following message:

`AttributeError: 'NoneType' object has no attribute 'close'`

## Code
You can reproduce the error with the following code.

```python
from PIL import Image
from pillow_heif import register_heif_opener

register_heif_opener()

image = Image.open("filename.heic")
image.verify()
```

## System Info
- OS: Mac BigSur & Debian 10
- Python 3.8.12
- Pillow 9.0.1
- pillow-heif 0.1.6

**Comment by ruixingchen** [comment]
`'NoneType' object has no attribute 'seek'`
I got this error when I call verify(), and this only happens on some of the image, don't know why
sample image 
https://www.loli.tc/image/qB41J
