### ISSUE TITLE
issue with heic files using Pillow-SIMD but not Pillow

### ISSUE THREAD

**Issue by jzstoller** [bigcat88/pillow_heif#176]
### Describe the bug

The script below works with pillow-10.1.0 but throws an error with Pillow-SIMD-9.0.0.post1

### Steps/Code to Reproduce

```
from PIL import Image
from pillow_heif import register_heif_opener

register_heif_opener()

im = Image.open('testimage.heic')
im.thumbnail((200, 200))
im.save('test.jpg', 'jpeg')
```

### Expected Results

No error is thrown using Pillow-SIMD

### Actual Results

PIL.UnidentifiedImageError: cannot identify image file "/Users/testuser/testimage.heic"

### Versions

```shell
3.11.5 (main, Sep  1 2023, 11:37:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS-13.6.1-x86_64-i386-64bit
0.13.1
{'libheif': '1.16.2', 'HEIF': 'x265 HEVC encoder (3.4+31-6722fce1f)', 'AVIF': 'AOMedia Project AV1 Encoder 3.7.0'}
```

**Comment by jzstoller** [comment]
Thank you! I downloaded pillow_simd 9.5.0 from github and installed. Now works perfectly.

Maybe have pillow_heif throw a warning if wrong Pillow version is installed?

**Comment by bigcat88** [comment]
> Maybe have pillow_heif throw a warning if wrong Pillow version is installed?

during install it is handled by **pip**: https://github.com/bigcat88/pillow_heif/blob/460a1b5a07dd859c2b9bdf0adc9ca06f92ae10a0/setup.cfg#L36-L40

> Now works perfectly.

glad to hear it, if something else will rise, feel free to create issue/discussion :)
