### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by dust-to-dust** [bigcat88/pillow_heif#19]
### Describe the bug

origin：as_opener.py  line58

`extensions = [".heic", ".hif"]`

I think it may be follow:

`extensions = [".heic", ".heif"]`

### Steps/Code to Reproduce

none

### Expected Results

none

### Actual Results

none

### Versions

```shell
none
```

**Comment by bigcat88** [comment]
There are images in test folder with `.hif` extension.
If you will find and post here images with `.heif` extension, i will be glad to look at those.
