### ISSUE TITLE
When do you expect to support saving?

### ISSUE THREAD

**Issue by bigcat88** [bigcat88/pillow_heif#20]
### Discussed in https://github.com/bigcat88/pillow_heif/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **dust-to-dust** March 21, 2022</sup>
I tried to convert the format, but find this only😂😂😂.

```
def write_heif():
    raise NotImplementedError("not done yet")
```</div>

**Comment by bigcat88** [comment]
@dust-to-dust, version with encoder was released :)
@XiaoqiangZhou maybe you will find this useful, too.(there is an example of encoding .gif to .heic)

P.S.: Pillow's encoder parameter: `append_images`  -  is not supported yet, maybe will be in 0.2.1 or 0.2.2. Depends if someone need it ot not.

**Comment by dust-to-dust** [comment]
OK, thank you very much.
