### ISSUE TITLE
Sigal support

### ISSUE THREAD

**Issue by bigcat88** [bigcat88/pillow_heif#22]
### Describe why it is important and where it will be useful

Currently investigating if it is needed...

### Describe your proposed solution

Adding file to pass to register as a plugin with Sigal

### Describe alternatives you've considered, if relevant

Registration of plugins-modules in Sigal
```python3

    for plugin in settings['plugins']:
        try:
            if isinstance(plugin, str):
                mod = importlib.import_module(plugin)
                mod.register(settings)
            else:
                plugin.register(settings)
            logger.debug('Registered plugin %s', plugin)
```

### Additional context

Will be good if someone who uses Sigal, says how to use it in proper way. And when to register `module` and when a `plugin`.

Like @Simon566 for example.

**Comment by bigcat88** [comment]
I will add autoregister option in next version.
But looks like Sigal for some reason don't see exif and other stuff(but able to resize it, so part of it working well).

**Comment by bigcat88** [comment]
@Simon566 

```python3
plugins = [
    "sigal.plugins.adjust",
    "sigal.plugins.copyright",
    "sigal.plugins.extended_caching",
    "sigal.plugins.feeds",
    "sigal.plugins.nomedia",
    "sigal.plugins.watermark",
    "sigal.plugins.zip_gallery",
    "pillow_heif.HeifImagePlugin"         # <--- auto registration of Pillow plugin, from version 0.2.2
]
```

For some reason it generates thumbnails for heic's and place originals in folders, and i see `pug_1_1.heic.html` but there is no pug_1_1.heic near it. That needs investigation after release `0.2.2` published, with someone who knows what that tests in `sigal` do, cause i don't(maybe that is a proper behaviour).

If you wish test it before release and not wait release that will be in a week, i will link commit with `HeifImagePlugin` file in a few hours.

**Comment by Simon566** [comment]
Hi,

thank you for the hint , now im a step further ! the plugin gets loaded as far as i can see, now i end up with:

INFO: Failed to process: UnidentifiedImageError("cannot identify image file '/home/simon/python_virt_sigal/BildTest/./001_Jakob_Gräf_1941.heic'")
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/gallery.py", line 961, in worker
    return process_file(args)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/gallery.py", line 953, in process_file
    return processor(media)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/image.py", line 188, in process_image
    generate_image(media.src_path, media.dst_path, media.settings, options=options)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/image.py", line 98, in generate_image
    img = _read_image(source)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/image.py", line 72, in _read_image
    im = PILImage.open(file_path)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/home/simon/python_virt_sigal/BildTest/./001_Jakob_Gräf_1941.heic'
"""

but the test code could successfully convert it, so the image is okay ....

**Comment by Simon566** [comment]
damn sorry, 

it doesnt discover the plugin .......

INFO: Aachen - Hochzeit Gräf, Bruder v Peter Gräf.jpeg exists - skipping
INFO: Processing /home/simon/python_virt_sigal/BildTest/./001_Jakob_Gräf_1941.heic
INFO: Processing /home/simon/python_virt_sigal/BildTest/./001_Jakob_Gräf_1941 - Kopie.heif
INFO: Failed to process: UnidentifiedImageError("cannot identify image file '/home/simon/python_virt_sigal/BildTest/./001_Jakob_Gräf_1941 - Kopie.heif'")
INFO: Failed to process: UnidentifiedImageError("cannot identify image file '/home/simon/python_virt_sigal/BildTest/./001_Jakob_Gräf_1941.heic'")
ERROR: Failed to load plugin pillow_heif.HeifImagePlugin: ModuleNotFoundError("No module named 'pillow_heif.HeifImagePlugin'")
Collecting albums, done.
  Sorting albums  [####################################]  100%
   Sorting media  [####################################]  100%
Collecting files  [####################################]  100%
Processing files  [####################################]  2/2
ERROR: Some files have failed to be processed:
ERROR:   - 001_Jakob_Gräf_1941.heic
ERROR:   - 001_Jakob_Gräf_1941 - Kopie.heif
ERROR: You can run "sigal build" in verbose (--verbose) or debug (--debug) mode to get more details.
   Writing files  [####################################]  100%

Done, processed 2 images (1 skipped, 2 failed) in 0.38 seconds.
(env) simon@odroidh2:~/python_virt_sigal$

**Comment by bigcat88** [comment]
yeah, wait till i commit that file to repo :)

**Comment by Simon566** [comment]
:-) rgr. thanks for your efforts

**Comment by bigcat88** [comment]
@Simon566 you free to build it from source and test now.
Or manually add that file `HeifImagePlugin.py` to pillow-heif that installed in `site-packages`

**Comment by Simon566** [comment]
Hi,

it looks like its missing a register method ?

INFO:       Source : /home/simon/python_virt_sigal/BildTest
INFO:  Destination : /home/simon/python_virt_sigal/website
INFO:        Theme : galleria
DEBUG: Plugin paths: []
ERROR: Failed to load plugin pillow_heif.HeifImagePlugin: AttributeError("module 'pillow_heif.HeifImagePlugin' has no attribute 'register'")
INFO: Using 4 cores
DEBUG: Albums:
dict_values([<Album>(path='.', title='BildTest')])
INFO: Aachen - Hochzeit Gräf, Bruder v Peter Gräf.jpeg exists - skipping
INFO: Aachen - Hochzeit Gräf, Bruder v Peter Gräf.tif exists - skipping
Traceback (most recent call last):
  File "/home/simon/python_virt_sigal/env/bin/sigal", line 8, in <module>
    sys.exit(main())
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/__init__.py", line 174, in build
    gal.build(force=force)
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/gallery.py", line 852, in build
    for status in self.pool.imap_unordered(worker, media_list):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'module' object

**Comment by Simon566** [comment]
sorry i had a typo . it works !

**Comment by bigcat88** [comment]
it generates a error in log, but it must work.
I am not sure that I need add `register` method, cause this project is not a plugin for `signal`.
I just added auto register like in all other Pillow's plugins.

**Comment by bigcat88** [comment]
@Simon566 will be good(imho) if you edit your messages to shorter in Pillow's topic.
Feel free to say if something work not as expected with `heif` files, here =)

**Comment by bigcat88** [comment]
@Simon566 can we close this?

**Comment by Simon566** [comment]
Hi,

almost. everything works BUT i do get a error from sigal about the "register" function of the plugin:


sigal output:

er, Frau Schwester von Katharina Gräf.tif'")
INFO: Failed to process: UnidentifiedImageError("cannot identify image file '/home/simon/python_virt_sigal/BildTest/./Bendorf - Hochzeit Kessler, Frau Schwester von Katharina Gräf_2.tif'")
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/simon/python_virt_sigal/env/lib/python3.9/site-packages/sigal/gallery.py", line 961, in worker
    return process_file(args)
ERROR: Failed to load plugin pillow_heif.HeifImagePlugin: AttributeError("module 'pillow_heif.HeifImagePlugin' has no attribute 'register'")
Collecting albums, done.
  Sorting albums  [####################################]  100%
   Sorting media  [####################################]  100%
Collecting files  [####################################]  100%
Processing files  [####################################]  7/7

the funny part is the processing works, even it gives a error message


regards,
Simon

**Comment by bigcat88** [comment]
@Simon566 look at https://github.com/saimn/sigal/issues/436#issuecomment-1152713321

Just put `import pillow_heif.HeifImagePlugin` inside your Sigal's conf.py file.

**Comment by bigcat88** [comment]
closing, solution how to make it work with Sigal is present, if any errors & bugs occurs - create new issue.
