### ISSUE TITLE
Opacity information is lost when reading a P mode image with transparency information

### ISSUE THREAD

**Issue by alexwlchan** [bigcat88/pillow_heif#235]
### Describe the bug

If you have a PNG image with mode `P` and a custom `transparency` value, opacity information is lost when you convert to HEIC.

### Steps/Code to Reproduce

```python
from PIL import Image, ImageDraw
from pillow_heif import register_heif_opener

register_heif_opener()

# Draw a basic checkerboard image
im = Image.new("P", size=(100, 100))

draw = ImageDraw.Draw(im)
draw.rectangle(xy=[(0, 0),   (50, 50)],   fill=255)
draw.rectangle(xy=[(50, 50), (100, 100)], fill=255)

# Save the image as a PNG, marking the 0'th colour in the palette as transparent
im.save("checkerboard.png", transparency=0)

# Open the image, then save it as an AVIF
opened_im = Image.open("checkerboard.png")
opened_im.save("checkerboard.heic", transparency=0)
```

### Expected Results

An image with a simple 2×2 checkerboard pattern, with transparent squares in the bottom left and top right.

### Actual Results

The HEIC is rendered as a solid black image, losing the transparency from the PNG.

<img width="526" alt="Screenshot 2024-04-29 at 22 39 05" src="https://github.com/bigcat88/pillow_heif/assets/301220/385f571c-29c7-4558-bf28-db99ba6413a0">

### Versions

```shell
3.11.8 (v3.11.8:db85d51d3e, Feb  6 2024, 18:02:37) [Clang 13.0.0 (clang-1300.0.29.30)]
macOS-13.6.6-x86_64-i386-64bit
0.16.0
{'libheif': '1.17.6', 'HEIF': 'x265 HEVC encoder (3.4+31-6722fce1f)', 'AVIF': 'AOMedia Project AV1 Encoder 3.8.1', 'encoders': {'x265': 'x265 HEVC encoder (3.4+31-6722fce1f)', 'aom': 'AOMedia Project AV1 Encoder 3.8.1', 'mask': 'mask'}, 'decoders': {'libde265': 'libde265 HEVC decoder, version 1.0.15', 'aom': 'AOMedia Project AV1 Decoder 3.8.1'}}
```

**Comment by alexwlchan** [comment]
Note: this may be related to https://github.com/fdintino/pillow-avif-plugin/issues/48, which is where I originally spotted this issue.

**Comment by bigcat88** [comment]
Corrected the behaviour when the transparency is `0`

_Thank you for the bug report._
