### ISSUE TITLE
Conflicting license metadata in setup.cfg

### ISSUE THREAD

**Issue by johncf** [bigcat88/pillow_heif#302]
It (presumably) incorrectly mentions GPLv2 and LGPLv3 in `setup.cfg`:

https://github.com/bigcat88/pillow_heif/blob/d3de7b580e1691a8c3c3e9027e004609d0678696/setup.cfg#L25

https://github.com/bigcat88/pillow_heif/blob/d3de7b580e1691a8c3c3e9027e004609d0678696/pi-heif/setup.cfg#L25

**Comment by bigcat88** [comment]
This is for binary wheels, `pi-heif` doest not have `x265` library bundled that have `GPLv2` license

**Comment by johncf** [comment]
Doesn’t that mean `pi-heif` can be BSD-3-clause? Both of those files also mentions:

https://github.com/bigcat88/pillow_heif/blob/d3de7b580e1691a8c3c3e9027e004609d0678696/pi-heif/setup.cfg#L29

**Comment by bigcat88** [comment]
BSD-3-Clause is a license for the source code of this project, because as far as I know (I could be wrong) BSD-3-Clause is a more free license than even LGPLv3, so it is not possible to use BSD-3-Clause on binary wheels?

**Comment by johncf** [comment]
Ah I see what you mean. Since the binary wheels of `pi-heif` and `pillow-heif` ships with a compiled version of [`libheif`](https://github.com/strukturag/libheif), which has LGPLv3 license, it must have a license that's at least as restrictive.

Closing this issue as things as it is was intentional. (Perhaps adding a note about the binary wheel licenses somewhere might be a good idea.)
