### ISSUE TITLE
Created jpg image is skewed diagonally, clearly incorrect

### ISSUE THREAD

**Issue by kevinlinxc** [bigcat88/pillow_heif#41]
### Describe the bug

I put in an heic that I know is not weird.

I run the example code below, and it saves a jpg that looks weird and skewed.

### Steps/Code to Reproduce

```python
# main.py
if __name__ == '__main__':
    path = "C:\\Users\\whatever\\myimg.heic"
    heif_file = pillow_heif.open_heif(path)
    image = Image.frombytes(heif_file.mode, heif_file.size, heif_file.data, "raw")
    image.save("hi.jpg")
```

### Expected Results

![image](https://user-images.githubusercontent.com/44324811/193359960-551faf5c-cbf3-467d-96d7-abb0ceae3123.png)

### Actual Results

![image](https://user-images.githubusercontent.com/44324811/193359980-4a74989e-041f-4ead-a5ac-9a7bf6944dee.png)

### Versions

```shell
Windows 10


0.7.0
{'version': {'libheif': '1.13.0', 'x265': 'x265 HEVC encoder (3.4+31-6722fce1f)', 'aom': 'AOMedia Project AV1 Encoder v3.4.0'}, 'decoders': {'HEVC': 1, 'AV1': 1, 'AVC': 0}, 'encoders': {'HEVC': 1, 'AV1': 1, 'AVC': 0}}
```

**Comment by kevinlinxc** [comment]
Using `register_heif_opener` instead fixed this problem. Still curious to know why.

**Comment by bigcat88** [comment]
You can use `to_pillow` method or look at  it source:
` image = Image.frombytes(
            self.mode,
            self.size,
            self.data,
            "raw",
            self.mode,
            self.stride,
)`

I think `stride` value will be different from width of image, and  that  is why such result when you not specified it.

**Comment by bigcat88** [comment]
@kevinlinxc 
```
if __name__ == '__main__':
    path = "C:\\Users\\whatever\\myimg.heic"
    heif_file = pillow_heif.open_heif(path)
    image = Image.frombytes(heif_file.mode, heif_file.size, heif_file.data, "raw", heif_file.mode, heif_file.stride)
    image.save("hi.jpg")
```
will be the correct code. if it works, then it is  just an invalid use.
