### ISSUE TITLE
Packaging as egg says "ModuleNotFoundError: No module named '_pillow_heif_cffi'"

### ISSUE THREAD

**Issue by melyux** [bigcat88/pillow_heif#73]
### Describe the bug

I wanted to make this usable on a system where I can't run `pip` to install this. I did the usual `python3 setup.py bdist_egg` and got an .egg file.

But upon trying to import something, I get:

```
  File "/etc/hooks/myScript.py", line 13, in <module>
    from pillow_heif import register_heif_opener
  File "/etc/hooks/./pillow_heif.egg/pillow_heif/__init__.py", line 7, in <module>
  File "/etc/hooks/./pillow_heif.egg/pillow_heif/_lib_info.py", line 5, in <module>
ModuleNotFoundError: No module named '_pillow_heif_cffi'
```

Same result with building a .whl with `python3 -m build`

### Steps/Code to Reproduce

Package as .egg and try to import it a pillow_heif module.

### Expected Results

I can use pillow_heif.

### Actual Results

I can't use pillow_heif.

### Versions

```shell
Python 3.10, Linux 64-bit, latest pillow_heif release
```

**Comment by bigcat88** [comment]
1. Install python CFFI before building
2. Run setup.py under root (if libheif library is not already installed in system, minimum supported `libheif` is `1.13.0`)

In `0.10.x` version(which will be `beta` of `1.0.0` release) there will be not dependent on `CFFI` module, but i can't say when the release will be(probably in a month), rewriting it all to `C` is still in a progress...

**Comment by bigcat88** [comment]
@melyux any success on this?

**Comment by melyux** [comment]
Hey @bigcat88 I went with using a virtualenv instead for this instead of using eggs/wheels. Are you saying the simple bdist commands should work in the future without having to do the extra CFFI install?

**Comment by bigcat88** [comment]
yep, i am working on this =)

**Comment by bigcat88** [comment]
@melyux feel free to test building from source. binary release on `pypi` will be available in a few days.

**Comment by bigcat88** [comment]
@melyux when after you check all is ok, feel free to close issue.
cheers :)

**Comment by melyux** [comment]
I will take your word for it! Thanks
