### ISSUE TITLE
Process get crashed with a corrupted file

### ISSUE THREAD

**Issue by bigcat88** [bigcat88/pillow_heif#79]
Based on this thread:

strukturag/libheif/issues/784

Tested it, and indeed it crashes the whole process.

Will try fix it in `0.10.0` upcoming release, will add additional check for image size after decoding.

**Comment by hackerfactor** [comment]
You should be able to replicate this crash by setting the ispe dimensions to be larger than the rendered dimensions. If the final output space is allocated based on the ispe dimensions, then you end up with a read overflow. (Read overflows are not great, but not too problematic.)

If the ispe dimensions are smaller than the rendered image, then -- depending on how you are copying the data -- it could result in a write-overflow. (Write overflows are bad, very bad.)
