### ISSUE TITLE
HEIF/AVIF file signature (magic number)

### ISSUE THREAD

**Issue by DimonLavron** [bigcat88/pillow_heif#8]
Hi there!

Recently I started to use [pyheif-pillow-opener](https://github.com/ciotto/pyheif-pillow-opener) for one project to add support for heif/avif files. It was great until I faced with some issue, that I want to share with you, because I can see you start developing your addon a month ago and you hopefully can fix it faster on your side

So, in [as_opener.py](https://github.com/bigcat88/pillow_heif/blob/master/pillow_heif/as_opener.py) you have `check_heif_magic` method. It checks, if 5-8 bytes of signature is ftyp or 9-12 bytes of signature is one of the listed brands, but I think it should be logical `and` instead of logical `or` in return statement and that's why:

1. Links in function comments [https://github.com/strukturag/libheif/issues/83](https://github.com/strukturag/libheif/issues/83) [https://github.com/GNOME/gimp/commit/e4bff4c8016f18195f9a6229f59cbf41740ddb8d](https://github.com/GNOME/gimp/commit/e4bff4c8016f18195f9a6229f59cbf41740ddb8d) shows, that acceptable magic numbers is ftypheic, ftypheix, ftypmif1 etc., not just ftyp or [heic, heix, mif1]
2. I found out that some other files can have 5-8 bytes as ftyp, for my particular situation it was .m4a, it has ftypM4A magic number, and I found some other files, that is not HEIF/AVIF photos, but have 5-8 bytes as ftyp (here you can find some them, but I bet we can find more: [https://www.garykessler.net/library/file_sigs.html](https://www.garykessler.net/library/file_sigs.html)) and because of that .m4a files can be validated as HEIF files with this function, but this is not HEIF at all

I can't find too much info about HEIF/AVIF file signature, so maybe I'm wrong, but from my experience and from discussions above I assume, that this could be a bug

Thank you for your attention, would be gladful if you fix this, or tell me that I've missed something!

**Comment by bigcat88** [comment]
Will look at this tomorrow.

**Comment by bigcat88** [comment]
@DimonLavron Release will be ready on Tuesday or Wednesday, need add some additional stuff, like caching in GitHub Actions for faster build(arm build takes too long time currently) and include libaom library for AV1 format, write tests for these images: [nokia heif repo](https://github.com/nokiatech/heif/tree/gh-pages/content) and maybe will have time to make windows binary bistro.

**Comment by DimonLavron** [comment]
@bigcat88 good to hear, thanks for quick reaction!

**Comment by bigcat88** [comment]
When they will fix this(https://github.com/pypa/cibuildwheel/issues/902) at the same day new version will be posted...
:(

**Comment by bigcat88** [comment]
@DimonLavron release published.

**Comment by DimonLavron** [comment]
@bigcat88 thanks a lot!

**Comment by bigcat88** [comment]
@DimonLavron published a new release(this is first version with windows wheels), there was some changes in opener mode(it must be faster now), can you please  check it ?
Tried to cover all with tests, but it is a bit complex task, need some more time for that.
