### ISSUE TITLE
Crash when trying to get exif image data

### ISSUE THREAD

**Issue by mxsleo** [bigcat88/pillow_heif#92]
### Describe the bug

When trying to apply the getexif() method to HEIF images made with my phone (stock Xiaomi), I get the error described below. As an example I've attached one of the problematic images: [image.zip](https://github.com/bigcat88/pillow_heif/files/11346285/image.zip) (sorry for using the zip format, uploading .heic files is not allowed).

### Steps/Code to Reproduce

```python
from PIL.Image import Exif, open as image_open
from pillow_heif import register_heif_opener

register_heif_opener()

with image_open("image.heic") as image:
    exif: Exif = image.getexif()
    print("Exif presents: {}".format(exif is not None))
```

### Expected Results

Exif presents: True | Exif presents: False

### Actual Results

Test machine 1:
```shell
Traceback (most recent call last):
  File "path-to-script.py", line 7, in <module>
    exif: Exif = image.getexif()
                 ^^^^^^^^^^^^^^^
  File "path-to-site-packages\PIL\Image.py", line 1455, in getexif
    self._exif.load(exif_info)
  File "path-to-site-packages\PIL\Image.py", line 3719, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path-to-site-packages\PIL\TiffImagePlugin.py", line 507, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b'\xff\xe18&Exif' not valid)
```

Test machine 2:
```shell
Traceback (most recent call last):
  File "path-to-script.py", line 7, in <module>
    exif: Exif = image.getexif()
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1275, in getexif
    self._exif.load(self.info.get("exif"))
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 3237, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v1(self.head)
  File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 900, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 466, in __init__
    raise SyntaxError("not a TIFF file (header %r not valid)" % ifh)
SyntaxError: not a TIFF file (header b'if\x00\x00II*\x00' not valid)
```

### Versions

```
Test machine 1:
3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
0.10.1
{'libheif': '1.15.2', 'HEIF': 'x265 HEVC encoder (3.4+31-6722fce1f)', 'AVIF': 'AOMedia Project AV1 Encoder v3.6.0'}

Test machine 1 additional information:
UTF-8 enabled for the whole system
Amernime Zone AMD 3rd party drivers
Pillow 9.5.0

Test machine 2:
3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]
Linux-5.15.0-71-generic-x86_64-with-glibc2.29
0.10.1
{'libheif': '1.15.2', 'HEIF': 'x265 HEVC encoder (3.5+1-f0c1022b6)', 'AVIF': 'AOMedia Project AV1 Encoder v3.5.0'}

Test machine 2 additional information:
VirtualBox VM Xubuntu 20.04 (clean install)
Pillow 7.0.0
```

**Comment by bigcat88** [comment]
Can I take this image to dataset for tests, e.g. what copyright does it have?

**Comment by mxsleo** [comment]
Of course, use it as you want. It is just a simple photo of nothing personal or copyright protected made by me with a camera application applying no additional copyright restrictions.

**Comment by bigcat88** [comment]
As Pillow do not have all tag id's for this image, you can use: `print(TAGS.get(k, "XXX"), ":", v)` to display it.

```python3
    exif = im.getexif()
    if exif:
        exif = exif._get_merged_dict()  # noqa
    for k, v in exif.items():
        if isinstance(v, bytes) and len(v) > 8:
            print(f"{TAGS[k]} : size {len(v)} bytes")
        else:
            print(TAGS.get(k, "XXX"), ":", v)
```

Can't promise that release will be in this week with fix, but in two weeks I will try to publish it, when will have what to fix more.

**Comment by mxsleo** [comment]
Thank you very much for the tip and for the fix! I will try this asap. Patiently waiting for the new release!

**Comment by bigcat88** [comment]
The error was bigger than I thought at first.
There was also incorrect handling of EXIF data when EXIF did not start with b`Exif\x00\x00`.
So, the new release fixes two EXIF bugs:

1. Correct handling when EXIF does not start with b`Exif\x00\x00`.
2. Adding support for some data before the actual EXIF data (your case of Xiaomi storing 4 bytes with something before the actual EXIF)

**Comment by mxsleo** [comment]
It's great to see, that the bug was fixed. Thank you very much for your work! I guess, we can now close this issue?...
